#!/usr/bin/env python3
"""Regenerate MANIFEST.md and per-source docs/<slug>/README.md from _manifest.json."""
from __future__ import annotations

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_ROOT = REPO_ROOT / "docs"
TOP_MANIFEST = REPO_ROOT / "MANIFEST.md"

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def topics_for_source(source_dir: Path) -> list[str]:
    return sorted(
        str(p.relative_to(source_dir).with_suffix(""))
        for p in source_dir.rglob("*.md")
        if p.name != "_manifest.json"
    )


def write_source_readme(source_dir: Path, slug: str, official_root: str, topics: list[str]) -> None:
    lines = [
        f"# {slug}",
        "",
        f"Mirrored from <{official_root}>. Do not edit by hand — regenerated by the fetch workflow.",
        "",
        f"**{len(topics)} topics**",
        "",
    ]
    for t in topics:
        lines.append(f"- {t}")
    (source_dir / "README.md").write_text("\n".join(lines) + "\n")


def main() -> int:
    if not DOCS_ROOT.exists():
        logger.error("no docs/ directory")
        return 1

    sources: list[tuple[str, str, list[str]]] = []
    for source_dir in sorted(p for p in DOCS_ROOT.iterdir() if p.is_dir()):
        manifest_path = source_dir / "_manifest.json"
        if not manifest_path.exists():
            logger.warning("skipping %s: no _manifest.json", source_dir.name)
            continue
        manifest = json.loads(manifest_path.read_text())
        topics = topics_for_source(source_dir)
        # Drop README from topic list since it's the TOC itself.
        topics = [t for t in topics if t != "README"]
        write_source_readme(source_dir, source_dir.name, manifest.get("official_root", ""), topics)
        sources.append((source_dir.name, manifest.get("official_root", ""), topics))

    lines = [
        "# data-live-docs — index",
        "",
        f"_Generated {datetime.now(timezone.utc).isoformat(timespec='minutes')}_",
        "",
        f"**{len(sources)} sources, {sum(len(t) for _, _, t in sources)} topics total**",
        "",
    ]
    for slug, official_root, topics in sources:
        lines.append(f"## {slug}")
        lines.append("")
        lines.append(f"Upstream: <{official_root}>")
        lines.append("")
        lines.append(f"_{len(topics)} topics_")
        lines.append("")
        for t in topics:
            lines.append(f"- `{slug}/{t}`")
        lines.append("")

    TOP_MANIFEST.write_text("\n".join(lines))
    logger.info("wrote %s (%d sources)", TOP_MANIFEST, len(sources))
    return 0


if __name__ == "__main__":
    sys.exit(main())
